In [1]:
import datasets
train_set = datasets.load_from_disk(dataset_path="./train")
print(train_set)
test_set = datasets.load_from_disk(dataset_path="./valid")
print(test_set[0])

word_train = []
y_train = []
for i in range(len(train_set)):
    word_train.append(train_set[i]["content"])
    y_train.append(train_set[i]["personality"])

word_test = []
y_test = []
for i in range(len(test_set)):
    word_test.append(test_set[i]["content"])
    y_test.append(test_set[i]["personality"])

print(word_test[0])
print(y_train[0])
print(word_train[0])
print(y_test[0])

Dataset({
    features: ['content', 'personality'],
    num_rows: 58972
})
{'content': "OH!The shame!It's unbearable.:P|||Aha...Well if it weren't for my superiority complex,I'd probably be down on the ground,all neurotic and depressive,locked up in an asylum.You need it in order to develop past your initial sphere of...|||Well excuse me for being such a drag.If it truly were a superiority complex,then I wouldn't be curious about the opinion of other people when it comes to understanding them.I just stated above that...|||I consider myself to be rather complicated.The mbti,jung's studies,psychology in general and philosophy inspired me to reach a certain conclusion related to people:if some are dumb,then it's not...|||I sometimes do simulate a large variety of things in my head resulting in intense feelings close to what I'd experience in reality.It's a bit complicated for me because while some people believe...|||I can't say I hate people.I always had trouble hating because I usually 

In [2]:
import re
import copy
import nltk
print(word_train[0])
s = re.split('[|,.":!@ ]', word_train[0])
l = []
for i in s:
    if i != '':
        l.append(i)
for j in range(len(l)):
    l[j] = l[j].lower()
print(l)

word_train_split = copy.deepcopy(word_train)
word_test_split = copy.deepcopy(word_test)
def sentence_split(words):
    for k in range(len(words)):
        s = re.split('[|,.":!@ ]', words[k])
        l = []
        for i in s:
            if i != '':
                l.append(i)
        for j in range(len(l)):
            l[j] = l[j].lower()
        words[k] = l


sentence_split(word_test_split)
sentence_split(word_train_split)
print(word_train_split[0])
print(word_test_split[0])
print(nltk.pos_tag(word_test_split[0]))

just watched the american in line in front of me search "barking ramz remix" on apple music|||@user that one's hot summer, hot hot summer|||girls aloud were right, it's gonna be a long hot summer|||for those that don't know i produce wank pop here you go link|||late to party but that spoken word lipsync was great|||lady in subway asked for "chipottle" sauce|||hey they gotta isaac emoji ‍|||boyfriend said "girl in front of fire" and meant this pic link|||@user my tweet refers exclusively to abortion and not sterilisation tho, i feel that this is a separate t… link|||what i mean to say is it's explicitly a women's rights issue - they are trying to regain total control over women's… link|||yes some men can get pregnant but restricting abortions is an act of oppression targeted at women specifically, and… link|||purchased hatsune miku game see you in a month|||enough link|||just said to myself "fishy fingers for the girly wirlies". i have a 39 degree fever|||will never understand people wh

In [3]:
import numpy as np
tags = ['CC', 'CD', 'DT', 'EX', 'FW', 'IN', 'JJ', 'JJR', 'JJS', 'LS', 'MD', 'NN', 'NNS', 'NNP', 'NNPS', 'PDT', 'POS', 'PRP', 'PRP$', 'RB', 'RBR', 'RBS', 'RP', 'TO', 'UH', 'VB', 'VBD', 'VBG', 'VBN', 'VBP', 'VBZ', 'WDT', 'WP', 'WP$', 'WRB']
n = len(tags)
x_train = np.zeros((len(word_train_split), n))
x_test = np.zeros((len(word_test_split), n))
for i in range(len(word_train_split)):
    word_tags = nltk.pos_tag(word_train_split[i])
    for x, y in word_tags:
        if y in tags:
            index_of_tags = tags.index(y)
            x_train[i][index_of_tags] += 1
for i in range(len(word_test_split)):
    word_tags = nltk.pos_tag(word_test_split[i])
    for x, y in word_tags:
        if y in tags:
            index_of_tags = tags.index(y)
            x_test[i][index_of_tags] += 1


In [4]:
for i in range(len(y_train)):
    l = [0, 0, 0, 0]
    s = str(y_train[i])
    if s[0] == 'I':
        l[0] = 1
    if s[1] == 'S':
        l[1] = 1
    if s[2] == 'T':
        l[2] = 1
    if s[3] == 'P':
        l[3] = 1
    y_train[i] = l
y1_train = []
y2_train = []
y3_train = []
y4_train = []
for i in range(len(y_train)):
    y1_train.append(y_train[i][0])
    y2_train.append(y_train[i][1])
    y3_train.append(y_train[i][2])
    y4_train.append(y_train[i][3])
for i in range(len(y_test)):
    l = [0, 0, 0, 0]
    s = str(y_test[i])
    if s[0] == 'I':
        l[0] = 1
    if s[1] == 'S':
        l[1] = 1
    if s[2] == 'T':
        l[2] = 1
    if s[3] == 'P':
        l[3] = 1
    y_test[i] = l
y1_test = []
y2_test = []
y3_test = []
y4_test = []
for i in range(len(y_test)):
    y1_test.append(y_test[i][0])
    y2_test.append(y_test[i][1])
    y3_test.append(y_test[i][2])
    y4_test.append(y_test[i][3])

In [5]:
x_train = np.array(x_train)
x_test = np.array(x_test)
def softmax(x):
    softmax_x = np.zeros(x.shape)
    for i in range(x.shape[0]):
        c = 0
        for j in range(x.shape[1]):
            c += x[i][j]
        for j in range(x.shape[1]):
            softmax_x[i][j] = x[i][j]/c
    return softmax_x
x_train = softmax(x_train)
x_test = softmax(x_test)

In [14]:
from sklearn.linear_model import LogisticRegression
from sklearn.neural_network import MLPClassifier
from sklearn.neighbors import KNeighborsClassifier
from sklearn import svm
#nlp_model1 = svm.SVC(C=1.0, kernel='rbf', gamma='auto')
nlp_model1 = MLPClassifier(solver='lbfgs', alpha=0.01, hidden_layer_sizes=(16,), random_state=1, max_iter=10000)
nlp_model1.fit(x_train, y1_train)
y1_pred = nlp_model1.predict(x_test)
nlp_model1.fit(x_train, y2_train)
y2_pred = nlp_model1.predict(x_test)
nlp_model1.fit(x_train, y3_train)
y3_pred = nlp_model1.predict(x_test)
nlp_model1.fit(x_train, y4_train)
y4_pred = nlp_model1.predict(x_test)
y_test = np.array(y_test)
y_pred = np.zeros(y_test.shape)
for i in range(len(y_test)):
    y_pred[i][0] = y1_pred[i]
    y_pred[i][1] = y2_pred[i]
    y_pred[i][2] = y3_pred[i]
    y_pred[i][3] = y4_pred[i]
acc = 0
for i in range(len(y_test)):
    if y_test[i][0] == y_pred[i][0] and y_test[i][1] == y_pred[i][1] and y_test[i][2] == y_pred[i][2] and y_test[i][3] == y_pred[i][3]:
        acc += 1
acc = acc/(len(y_test))
print(acc)



0.18266752577319587


In [19]:
y_train_split = np.zeros((len(y_train), 16))
for i in range(len(y_train)):
    k = y1_train[i] * 1 + y2_train[i] * 2 + y3_train[i] * 4 + y4_train[i] * 8
    y_train_split[i][k] = 1
y_test_split = np.zeros((len(y_test), 16))
for i in range(len(y_test)):
    k = y1_test[i] * 1 + y2_test[i] * 2 + y3_test[i] * 4 + y4_test[i] * 8
    y_test_split[i][k] = 1
nlp_model2 = KNeighborsClassifier()
nlp_model2.fit(x_train, y_train_split)
y_pred_split = nlp_model2.predict(x_test)
acc2 = 0
for i in range(len(y_test_split)):
    k = 0
    for j in range(16):
        if y_test_split[i][j] == y_pred_split[i][j]:
            k += 1
    if k == 16:
        acc2 += 1
print(y_train_split)
print(y_pred_split[0])
print(y_test_split[0])
acc2 = acc2/len(y_test_split)
print(acc2)

[[0. 0. 0. ... 1. 0. 0.]
 [0. 0. 0. ... 0. 0. 0.]
 [0. 0. 0. ... 0. 0. 0.]
 ...
 [1. 0. 0. ... 0. 0. 0.]
 [0. 0. 0. ... 0. 0. 0.]
 [0. 1. 0. ... 0. 0. 0.]]
[0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
[0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 1. 0. 0.]
0.03125


In [18]:
print(y_train_split.shape)
print(y_pred_split.shape)
print(x_train[0])
ss = 0
for i in x_train[0]:
    ss += i
for i in range(len(y_train_split)):
    c = 0
    for j in range(16):
        if y_train_split[i][j] == 1:
            c = 1
    if c == 0:
        print("error")
        break

(58972, 16)
(3104, 16)
[0.02105263 0.00701754 0.07368421 0.         0.         0.09473684
 0.13333333 0.         0.00350877 0.         0.00701754 0.23157895
 0.04561404 0.00350877 0.         0.         0.         0.04561404
 0.01052632 0.05614035 0.         0.         0.00350877 0.02105263
 0.         0.05263158 0.02807018 0.02105263 0.02105263 0.08070175
 0.01754386 0.00701754 0.00701754 0.         0.00701754]
